# Generated by Django 2.2.7 on 2019-11-30 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_produto', models.CharField(max_length=80)),
                ('marca', models.CharField(max_length=80)),
                ('codigo_produto', models.CharField(max_length=1000)),
                ('preco', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('disponivel', models.BooleanField(default=True)),
                ('quantidade', models.IntegerField(default=1)),
                ('categoria', models.CharField(choices=[('alimentacao', 'Alimentação'), ('acessorios', 'Acessórios'), ('higiene', 'Higiene'), ('brinquedos', 'Brinquedos')], max_length=2)),
                ('descricao', models.CharField(max_length=400)),
            ],
        ),
    ]
