# Generated by Django 2.2.7 on 2019-11-30 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rapidog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='imagem',
            field=models.ImageField(blank=True, null=True, upload_to='media/'),
        ),
        migrations.AlterField(
            model_name='produto',
            name='categoria',
            field=models.CharField(choices=[('alimentacao', 'Alimentação'), ('acessorios', 'Acessórios'), ('higiene', 'Higiene'), ('brinquedos', 'Brinquedos')], max_length=15),
        ),
    ]
