# Generated by Django 2.2.7 on 2019-11-30 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rapidog', '0003_auto_20191130_0333'),
    ]

    operations = [
        migrations.CreateModel(
            name='Loja',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_loja', models.CharField(max_length=100)),
                ('descricao_loja', models.CharField(max_length=400)),
                ('endereco', models.CharField(max_length=200)),
                ('bairro', models.CharField(choices=[('Bela Vista', 'Bela Vista'), ('Consolação', 'Consolação'), ('Jd Paulista', 'Jardim Paulista'), ('Perdizes', 'Perdizes'), ('Vila Mariana', 'Vila Mariana')], max_length=30)),
                ('cidade', models.CharField(choices=[('SAO', 'São Paulo')], max_length=30)),
                ('estado', models.CharField(choices=[('SP', 'SP')], max_length=2)),
                ('verificado', models.BooleanField(default=True)),
                ('logotipo', models.ImageField(blank=True, null=True, upload_to='')),
            ],
        ),
    ]
