# Generated by Django 2.2.7 on 2019-11-30 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rapidog', '0005_servico'),
    ]

    operations = [
        migrations.AddField(
            model_name='loja',
            name='banho',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='loja',
            name='combo',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='loja',
            name='preco_banho',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='loja',
            name='preco_combo',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='loja',
            name='preco_tosa',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='loja',
            name='tosa',
            field=models.BooleanField(default=True),
        ),
        migrations.DeleteModel(
            name='Servico',
        ),
    ]
