# Generated by Django 2.2.7 on 2019-12-01 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rapidog', '0006_auto_20191130_1816'),
    ]

    operations = [
        migrations.AddField(
            model_name='loja',
            name='anunciar',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='loja',
            name='anuncio',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
