<<<<<<< HEAD
# Generated by Django 2.2.7 on 2019-12-03 23:36
=======
# Generated by Django 2.2.7 on 2019-12-02 16:57
>>>>>>> af7fe1bdf29e9b42a15f643380c12c82b88a27c0

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rapidog', '0007_auto_20191201_1648'),
    ]

    operations = [
        migrations.CreateModel(
            name='Newsletter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
<<<<<<< HEAD
                ('email', models.EmailField(max_length=140)),
=======
                ('nome', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
>>>>>>> af7fe1bdf29e9b42a15f643380c12c82b88a27c0
            ],
        ),
    ]
