# Generated by Django 2.2.8 on 2019-12-05 01:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rapidog', '0008_newsletter'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Newsletter',
        ),
    ]
