# Generated by Django 2.2.8 on 2019-12-05 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rapidog', '0009_delete_newsletter'),
    ]

    operations = [
        migrations.CreateModel(
            name='Newsletter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=140)),
            ],
        ),
    ]
