# Generated by Django 2.2.8 on 2019-12-11 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rapidog', '0015_auto_20191210_1904'),
    ]

    operations = [
        migrations.AddField(
            model_name='loja',
            name='codigo_loja',
            field=models.CharField(blank=True, max_length=1000),
        ),
    ]
